"""Add documents table and update chunk_embeddings for document support

Revision ID: 09072329e327
Revises: 1be28b31ddf6
Create Date: 2025-11-09 20:52:36.055919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09072329e327'
down_revision = '1be28b31ddf6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('modality_id', sa.String(length=36), nullable=False),
    sa.Column('submodality_id', sa.String(length=36), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['modality_id'], ['modalities.id'], ),
    sa.ForeignKeyConstraint(['submodality_id'], ['submodalities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chunk_embeddings', sa.Column('document_id', sa.String(length=36), nullable=True, comment='ID of the associated document'))
    op.alter_column('chunk_embeddings', 'question_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True,
               existing_comment='ID of the associated question')
    op.create_index(op.f('ix_chunk_embeddings_document_id'), 'chunk_embeddings', ['document_id'], unique=False)
    op.create_foreign_key(None, 'chunk_embeddings', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chunk_embeddings', type_='foreignkey')
    op.drop_index(op.f('ix_chunk_embeddings_document_id'), table_name='chunk_embeddings')
    op.alter_column('chunk_embeddings', 'question_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False,
               existing_comment='ID of the associated question')
    op.drop_column('chunk_embeddings', 'document_id')
    op.drop_table('documents')
    # ### end Alembic commands ###
