"""clean_migration

Revision ID: 1be28b31ddf6
Revises: a1b2c3d4e5f6
Create Date: 2025-11-06 01:28:16.021989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1be28b31ddf6'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_config',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('greeting_message', sa.Text(), nullable=False),
    sa.Column('greeting_enabled', sa.Boolean(), nullable=True),
    sa.Column('office_name', sa.String(length=255), nullable=True),
    sa.Column('faculty_name', sa.String(length=255), nullable=True),
    sa.Column('university_name', sa.String(length=255), nullable=True),
    sa.Column('campus_location', sa.String(length=255), nullable=True),
    sa.Column('building_name', sa.String(length=255), nullable=True),
    sa.Column('floor_office', sa.String(length=100), nullable=True),
    sa.Column('street_address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('director_name', sa.String(length=60), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('office_hours', sa.Text(), nullable=True),
    sa.Column('social_facebook', sa.String(length=255), nullable=True),
    sa.Column('social_instagram', sa.String(length=255), nullable=True),
    sa.Column('social_twitter', sa.String(length=255), nullable=True),
    sa.Column('social_youtube', sa.String(length=255), nullable=True),
    sa.Column('social_linkedin', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chatbot_config')
    # ### end Alembic commands ###
