"""Add modality_id to categories and make submodality_id nullable

Revision ID: e8a02ff92ec2
Revises: 09072329e327
Create Date: 2025-11-11 21:07:03.638377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8a02ff92ec2'
down_revision = '09072329e327'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('modality_id', sa.String(length=36), nullable=True))
    op.alter_column('categories', 'submodality_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_foreign_key(None, 'categories', 'modalities', ['modality_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.alter_column('categories', 'submodality_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('categories', 'modality_id')
    # ### end Alembic commands ###
