"""initial_clean_schema

Revision ID: ed67d9223762
Revises: 
Create Date: 2025-09-21 18:42:13.930811

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = 'ed67d9223762'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modalities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modalities_name'), 'modalities', ['name'], unique=False)
    op.create_index(op.f('ix_modalities_slug'), 'modalities', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('reset_token', sa.String(length=100), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('submodalities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('modality_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['modality_id'], ['modalities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submodalities_name'), 'submodalities', ['name'], unique=False)
    op.create_index(op.f('ix_submodalities_slug'), 'submodalities', ['slug'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('submodality_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['submodality_id'], ['submodalities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('context_text', sa.Text(), nullable=True),
    sa.Column('context_type', sa.String(length=20), nullable=False),
    sa.Column('context_file', sa.String(length=500), nullable=True),
    sa.Column('modality_id', sa.String(length=36), nullable=False),
    sa.Column('submodality_id', sa.String(length=36), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('model_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['modality_id'], ['modalities.id'], ),
    sa.ForeignKeyConstraint(['submodality_id'], ['submodalities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chunk_embeddings',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique identifier of the chunk embedding'),
    sa.Column('question_id', sa.String(length=36), nullable=False, comment='ID of the associated question'),
    sa.Column('chunk_text', sa.Text(), nullable=False, comment='Processed chunk text'),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), nullable=False, comment='Vector embedding of 384 dimensions (all-MiniLM-L6-v2)'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='Index of the chunk within the document'),
    sa.Column('chunk_size', sa.Integer(), nullable=True, comment='Size of the chunk in characters'),
    sa.Column('chunk_metadata', sa.Text(), nullable=True, comment='Additional metadata of the chunk in JSON format'),
    sa.Column('processing_model', sa.String(length=100), nullable=True, comment='Model used to generate the embedding'),
    sa.Column('processing_version', sa.String(length=50), nullable=True, comment='Version of the processing model'),
    sa.Column('similarity_score', sa.String(length=50), nullable=True, comment='Similarity score (calculated in queries)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation date'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Last update date'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunk_embeddings_question_id'), 'chunk_embeddings', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunk_embeddings_question_id'), table_name='chunk_embeddings')
    op.drop_table('chunk_embeddings')
    op.drop_table('questions')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_submodalities_slug'), table_name='submodalities')
    op.drop_index(op.f('ix_submodalities_name'), table_name='submodalities')
    op.drop_table('submodalities')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_modalities_slug'), table_name='modalities')
    op.drop_index(op.f('ix_modalities_name'), table_name='modalities')
    op.drop_table('modalities')
    # ### end Alembic commands ###
